### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by blaackpanter** [Konev-I/Autotests#1]
Это общий момент для всех тестов, нужно вынести в отдельный класс, например, BaseTest в метод before.
https://github.com/Konev-I/Autotests/blob/d80e888c46185f18fa9664bf4f196c9b2ef97bb8/src/test/java/org/test/tests/LoginTest.java#L23

Не надо так сокращаться пейджи.
https://github.com/Konev-I/Autotests/blob/d80e888c46185f18fa9664bf4f196c9b2ef97bb8/src/test/java/org/test/tests/LoginTest.java#L24

Это общий момент для всех тестов, нужно вынести в отдельный класс, например, BaseTest в метод after.
https://github.com/Konev-I/Autotests/blob/d80e888c46185f18fa9664bf4f196c9b2ef97bb8/src/test/java/org/test/tests/LoginTest.java#L31

Вынести в переменную.
https://github.com/Konev-I/Autotests/blob/d80e888c46185f18fa9664bf4f196c9b2ef97bb8/src/test/java/org/test/tests/MessageSendingTest.java#L35

Вынести в переменные (здесь, дальше и во всех классах).
https://github.com/Konev-I/Autotests/blob/d80e888c46185f18fa9664bf4f196c9b2ef97bb8/src/test/java/org/test/pages/LoginPage.java#L19

Тулбару враппер не нужен. Там разные элементы, у которых разные локаторы, разные названия и т.д.
https://github.com/Konev-I/Autotests/blob/d80e888c46185f18fa9664bf4f196c9b2ef97bb8/src/test/java/org/test/pages/wrappers/ToolbarWrapper.java#L8

**Comment by Konev-I** [comment]
@blaackpanter 

Я исправил:
- Вынес открытие страницы ok.ru и закрытие окна в отдельный класс BaseTest; 
- Изменил сокращённые названия для переменных в которых хранятся страницы;
- Вынес в отдельную переменную найденный по локатору элемент, а затем уже использую его методы.

Но хотелось бы обсудить следующие замечания:
Здесь я хотел использовать паттерн "Chain of invocations", который нас просили использовать. Из названия методов понятно что происходит и идёт вызов только двух методов подряд, что не перегружает восприятие кода. Или всё равно не стоит так делать?
https://github.com/Konev-I/Autotests/blob/d80e888c46185f18fa9664bf4f196c9b2ef97bb8/src/test/java/org/test/tests/MessageSendingTest.java#L35

А про тулбар я думал так, он есть на нескольких страницах (например, в ленте, друзьях, фото, группах и т.д.) и на его кнопки (например открытия сообщений, обсуждений, оповещений, музыки и т.д.) можно будет нажимать с любой страницы на которой он есть, поэтому чтобы не прописывать локаторы для этих кнопок на всех страницах можно просто будет создать объект этого враппера и вызвать метод нажатия на кнопку. Конечно, в моих тестах используется всего одна кнопка из набора, но если они мне потребуются, то я добавлю остальные. 
https://github.com/Konev-I/Autotests/blob/d80e888c46185f18fa9664bf4f196c9b2ef97bb8/src/test/java/org/test/pages/wrappers/ToolbarWrapper.java#L8

**Comment by blaackpanter** [comment]
BaseTest вижу, урл в переменную.
https://github.com/Konev-I/Autotests/blob/9f3520d58a9b1e3a5a75fb3825117ac51ae6bf3c/src/test/java/org/test/tests/BaseTest.java#L12

По всему коду пройтись и все вынести.
https://github.com/Konev-I/Autotests/blob/9f3520d58a9b1e3a5a75fb3825117ac51ae6bf3c/src/test/java/org/test/tests/LoginTest.java#L15

А вот здесь правильно, текст оставить в assert, потому что в случае его выноса затруднится поиск ошибки.
https://github.com/Konev-I/Autotests/blob/9f3520d58a9b1e3a5a75fb3825117ac51ae6bf3c/src/test/java/org/test/tests/LoginTest.java#L23

Почему в init()?
https://github.com/Konev-I/Autotests/blob/9f3520d58a9b1e3a5a75fb3825117ac51ae6bf3c/src/test/java/org/test/tests/NoteCreationTest.java#L24

Про тулбар.
Ты правильно написал, что он есть на всех страницах. НО локаторы каждой кнопки(открытия сообщений, обсуждений, оповещений, музыки и т.д) придется прописывать все равно. Нельзя сделать какой-то список и по номеру условно обращаться (или по тексту). Очень часто страницы меняются, тулбар в том числе. Элементы могут поменяться местами, удалиться, добавиться новые, тексты тоже могут поменяться. В какой-то момент ты можешь ожидать один элемент, а там будет другой. Переход по локатору позволяет некоторых моментов избежать от падения теста. Поэтому в твоем случае надо просто убрать из названия "wrapper" и вынести из этой папки. В тулбаре должно быть столько методов goToMessages/Discussions/...(), столько элементов в нем самом на странице. И для каждого элемента в методе свой локатор. Надеюсь, стало понятнее. Враппер подходит для обертки песен, видео, людей в поиске и тд.

" можно будет нажимать с любой страницы на которой он есть, поэтому чтобы не прописывать локаторы для этих кнопок на всех страницах можно просто будет создать объект этого враппера и вызвать метод нажатия на кнопку." - все правильно, только это не враппер :)


Не очень понимаю, в чем здесь вопрос.
"Но хотелось бы обсудить следующие замечания:
Здесь я хотел использовать паттерн "Chain of invocations", который нас просили использовать. Из названия методов понятно что происходит и идёт вызов только двух методов подряд, что не перегружает восприятие кода. Или всё равно не стоит так делать?"
Я написала "Спутник" вынести в переменную. Все остальное правильно использовано.

**Comment by blaackpanter** [comment]
В своем ревью первом я тебе написала вынести тут текст в переменную. Вижу, ты не вынес. Правильно, в because текст аналогично с ассерт выносить не надо.
https://github.com/Konev-I/Autotests/blob/d80e888c46185f18fa9664bf4f196c9b2ef97bb8/src/test/java/org/test/pages/LoginPage.java#L19

**Comment by Konev-I** [comment]
@blaackpanter 

* Вынес url в переменную;
* Вынес текст для инициализации пользователя в поля теста, оставив только нужные для каждого теста;
* Убрал инициализацию заголовка и тела поста из init();
* Переименовал ToolbarWrapper в Toolbar, вынес его из пакета врапперов, добавил в него xpath и методы для всех кнопок;
* Вынес название чата "Спутник" в переменную;

**Comment by blaackpanter** [comment]
Все ок, можно закрывать issue.
